
//------------------------------------------------------------------------------
//
// Опции настройки компиляции
//
//------------------------------------------------------------------------------

// mode DEBUG (лог событий в отдельном окне IDE)
//  Allows you to view the event log in a separate window
//  `View` -> `IDE Internals` -> `[eventLog] $(PkgName)`
{.$define in0k_LazarusIdeEXT__DEBUG}


